### ISSUE TITLE
ionic-materia in phonegap problems

### ISSUE THREAD

**Issue by rafapetit** [zachsoft/Ionic-Material#119]
My app starts properly.
But when you press any button, I get this error.
You know anything about this.

[phonegap] [console.error] TypeError: Object #<HTMLButtonElement> has no method 'remove'
[phonegap]     at n.$scope.clearFabs (file:///data/data/com.adobe.phonegap.app/files/files/phonegapdevapp/www/js/controllers.js:85:21)
[phonegap]     at new <anonymous> (file:///data/data/com.adobe.phonegap.app/files/files/phonegapdevapp/www/js/controllers.js:109:20)
[phonegap]     at e (file:///data/data/com.adobe.phonegap.app/files/files/phonegapdevapp/www/lib/angular/angular.min.js:36:315)
[phonegap]     at Object.instantiate (file:///data/data/com.adobe.phonegap.app/files/files/phonegapdevapp/www/lib/angular/angular.min.js:36:432)
[phonegap]     at file:///data/data/com.adobe.phonegap.app/files/files/phonegapdevapp/www/lib/angular/angular.min.js:76:49
[phonegap]     at self.appendViewElement (file:///data/data/com.adobe.phonegap.app/files/files/phonegapdevapp/www/lib/ionic/js/ionic.bundle.js:47357:24)
[phonegap]     at Object.switcher.render (file:///data/data/com.adobe.phonegap.app/files/files/phonegapdevapp/www/lib/ionic/js/ionic.bundle.js:45614:41)
[phonegap]     at Object.switcher.init (file:///data/data/com.adobe.phonegap.app/files/files/phonegapdevapp/www/lib/ionic/js/ionic.bundle.js:45534:20)
[phonegap]     at self.render (file:///data/data/com.adobe.phonegap.app/files/files/phonegapdevapp/www/lib/ionic/js/ionic.bundle.js:47231:14)
[phonegap]     at self.register (file:///data/data/com.adobe.phonegap.app/files/files/phonegapdevapp/www/lib/ionic/js/ionic.bundle.js:47189:10)

Greetings and thanks for your time.
Rafa Petit

**Comment by kashban** [comment]
Well, with the code from /www/js/controllers.js somebody might be able to answer you.
