### ISSUE TITLE
fians/Ink.git 404

### ISSUE THREAD

**Issue by alexsalas** [zachsoft/Ionic-Material#123]
```sh
[03:49:30] 'install' errored after 7.16 s
[03:49:30] Error: Failed to execute "git ls-remote --tags --heads https://github.com/fians/Ink.git", exit code of #128
remote: Repository not found.
fatal: repository 'https://github.com/fians/Ink.git/' not found

    at createError (/.../Ionic-Material/demo/node_modules/bower/lib/util/createError.js:4:15)
    at ChildProcess.<anonymous> ((/.../Ionic-Material/demo/node_modules/bower/lib/util/cmd.js:102:21)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
$ git ls-remote --tags --heads https://github.com/fians/Ink.git
remote: Repository not found.
fatal: repository 'https://github.com/fians/Ink.git/' not found
```

**Comment by alexsalas** [comment]
@fians :point_up_2:

**Comment by fians** [comment]
@alexsalas I think there is mistake made by the author/creator since I never have a project or repository called Ink.

**Comment by gabrielbiga** [comment]
I fixed the dep misspelled.
Test this PR: https://github.com/zachsoft/Ionic-Material/pull/136

Cheers.

**Comment by oscarmcm** [comment]
Fixed :smile:
