### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by herve1976** [zachsoft/Ionic-Material#83]
ionic $ serve  /templates/gallery.html
serve  /templates/friends.html
serve  /templates/menu.html
serve  /img/crown.jpg
0     736849   error    Error: [$injector:unpr] Unknown provider: ionicMaterialInkProvider <- ionicMaterialInk <- LoginCtrl
http://errors.angularjs.org/1.3.13/$injector/unpr?p0=ionicMaterialInkProvider%20%3C-%20ionicMaterialInk%20%3C-%20LoginCtrl
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:7988:12
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:11922:19
    at Object.getService [as get] (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12069:39)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:11927:45
    at getService (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12069:39)
    at invoke (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12101:13)
    at Object.instantiate (http://localhost:8100/lib/ionic/js/ionic.bundle.js:12118:27)
    at http://localhost:8100/lib/ionic/js/ionic.bundle.js:16387:28
    at self.appendViewElement (http://localhost:8100/lib/ionic/js/ionic.bundle.js:47357:24)
    at Object.switcher.render (http://localhost:8100/lib/ionic/js/ionic.bundle.js:45614:41), <ion-nav-view name="menuContent" ng-class="{expanded: isExpanded}" class="view-container" nav-view-transition="ios">
serve  /img/login.jpg
serve  /lib/ionic/fonts/ionicons.ttf?v=2.0.1
serve  /templates/activity.html

**Comment by edencoder** [comment]
I believe this was fixed [fix issue11 & issue58 #82](https://github.com/zachsoft/Ionic-Material/issues/58#issuecomment-109729965)

**Comment by babakness** [comment]
Not working for me either.

**Comment by niwasmala** [comment]
Yes, it was fixed in #11 and #90, please check the working solution.
